### ISSUE TITLE
POST "/rules/{ruleId}" returns 404

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-results-smart-proxy#71]
Debug endpoints for rules stopped working.  POST "/rules/{ruleId}" returns 404.

Actual result:
Status code 404

Expected result:
Status code 200 and the rule should be added into the DB.

**Comment by joselsegura** [comment]
Since we moved all the static content from aggregator to the content-service, there is not an endpoint for creating rules into the DB, because right now they are not stored in the database anymore.

If you think it is necessary to keep this function (IIRC it was only for testing purposes), we can create an endpoint that allows adding new rule content to the memory structured in the smart proxy. WDYT?

**Comment by quarckster** [comment]
I see, then I will use a real rule id in the tests.
